# Generated by Django 4.1.4 on 2022-12-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modeluse", "0002_account_delete_friend"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="account_image",
        ),
        migrations.RemoveField(
            model_name="account",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="account",
            name="last_name",
        ),
        migrations.AddField(
            model_name="account",
            name="ObjsUrls",
            field=models.TextField(blank=True),
        ),
    ]
