# Generated by Django 4.1.4 on 2022-12-23 07:21

from django.db import migrations, models
import modeluse.models


class Migration(migrations.Migration):

    dependencies = [
        ("modeluse", "0003_remove_account_account_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NiftyFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attach",
                    models.FileField(
                        upload_to=modeluse.models.savePath, verbose_name="添付ファイル"
                    ),
                ),
            ],
        ),
    ]
