# Generated by Django 4.1.4 on 2022-12-23 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("modeluse", "0004_niftyfile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="niftyfile",
            old_name="attach",
            new_name="file",
        ),
    ]
