# Generated by Django 4.1.4 on 2022-12-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modeluse", "0006_niftyfile_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
            ],
        ),
    ]
