# Generated by Django 4.1.4 on 2022-12-23 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("modeluse", "0007_objfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="objfile",
            name="niftyfile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="modeluse.niftyfile",
            ),
            preserve_default=False,
        ),
    ]
