# Generated by Django 4.1.4 on 2022-12-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modeluse", "0008_objfile_niftyfile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="objfile",
            name="url",
        ),
        migrations.AddField(
            model_name="objfile",
            name="file",
            field=models.FileField(default=1, upload_to=""),
            preserve_default=False,
        ),
    ]
